spring.application.name=bff-service

server.port=8080

# URLs de los microservicios internos
usuarios.service.url=http://localhost:8082
academico.service.url=http://localhost:8081
asistencia.service.url=http://localhost:8083

# Auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-hnxz55jjtq1inapb.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://libro-digital-api

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true